export const destinations = [
  {
    id: 'xinghai',
    name: '星海广场',
    type: 'square',
    shortDesc: '亚洲最大的城市广场，大连的城市标志。',
    desc: '星海广场是亚洲最大的城市广场，位于大连南部海滨风景区，是大连市的城市标志之一。广场中心有全国最大的汉白玉华表，周边有百年城雕、游乐场等设施，是游客必去之地。',
    image: 'https://picsum.photos/seed/xinghai/800/600',
    gallery: [
      'https://picsum.photos/seed/xinghai1/800/600',
      'https://picsum.photos/seed/xinghai2/800/600',
      'https://picsum.photos/seed/xinghai3/800/600',
    ],
    price: '免费',
    time: '全天',
  },
  {
    id: 'tiger-beach',
    name: '老虎滩海洋公园',
    type: 'park',
    shortDesc: '国家5A级旅游景区，展示极地海洋动物。',
    desc: '大连老虎滩海洋公园坐落于大连南部海滨中部，是市区南部最大的景区。这里有极地馆、珊瑚馆、鸟语林等多个场馆，可以近距离观赏白鲸、海豚、企鹅等珍稀海洋动物。',
    image: 'https://picsum.photos/seed/tiger/800/600',
    gallery: [
      'https://picsum.photos/seed/tiger1/800/600',
      'https://picsum.photos/seed/tiger2/800/600',
      'https://picsum.photos/seed/tiger3/800/600',
    ],
    price: '¥220',
    time: '08:00-17:00',
  },
  {
    id: 'discoveryland',
    name: '发现王国主题公园',
    type: 'park',
    shortDesc: '充满异域风情的大型主题游乐园。',
    desc: '发现王国主题公园位于金石滩国家旅游度假区内，是一个充满异域风情的大型主题游乐园。拥有疯狂小镇、神秘沙漠、金属工厂等多个主题区，游乐设施惊险刺激，夜场还有精彩的烟花表演。',
    image: 'https://picsum.photos/seed/discovery/800/600',
    gallery: [
      'https://picsum.photos/seed/discovery1/800/600',
      'https://picsum.photos/seed/discovery2/800/600',
      'https://picsum.photos/seed/discovery3/800/600',
    ],
    price: '¥220',
    time: '09:30-21:00',
  },
  {
    id: 'golden-pebble',
    name: '金石滩国家旅游度假区',
    type: 'beach',
    shortDesc: '大连的后花园，拥有奇特的海岸地貌。',
    desc: '金石滩是大连的后花园，拥有十里黄金海岸、地质博物馆、发现王国等众多景点。这里的海岸地貌奇特，被誉为“神力雕塑公园”。',
    image: 'https://picsum.photos/seed/golden/800/600',
    gallery: [
      'https://picsum.photos/seed/golden1/800/600',
      'https://picsum.photos/seed/golden2/800/600',
      'https://picsum.photos/seed/golden3/800/600',
    ],
    price: '免费（部分景点收费）',
    time: '全天',
  },
  {
    id: 'bangchuidao',
    name: '棒棰岛',
    type: 'beach',
    shortDesc: '风景秀丽的国宾馆所在地，海水清澈。',
    desc: '棒棰岛位于大连市东端，是一处以山、海、岛、滩为主要景观的风景胜地。这里海水清澈，沙滩洁净，是国家领导人避暑疗养的地方。',
    image: 'https://picsum.photos/seed/bangchuidao/800/600',
    gallery: [
      'https://picsum.photos/seed/bangchuidao1/800/600',
      'https://picsum.photos/seed/bangchuidao2/800/600',
      'https://picsum.photos/seed/bangchuidao3/800/600',
    ],
    price: '¥20',
    time: '08:00-17:00',
  },
  {
    id: 'binhai-road',
    name: '滨海路',
    type: 'park',
    shortDesc: '大连最美的海滨公路，适合徒步和自驾。',
    desc: '滨海路全长30多公里，一边是连绵的山脉，一边是浩瀚的大海，风景极其优美。沿途有燕窝岭、北大桥等景点，是徒步和自驾的绝佳路线。',
    image: 'https://picsum.photos/seed/binhai/800/600',
    gallery: [
      'https://picsum.photos/seed/binhai1/800/600',
      'https://picsum.photos/seed/binhai2/800/600',
      'https://picsum.photos/seed/binhai3/800/600',
    ],
    price: '免费',
    time: '全天',
  },
  {
    id: 'venice',
    name: '东港威尼斯水城',
    type: 'square',
    shortDesc: '充满欧洲风情的运河水城。',
    desc: '东港威尼斯水城以威尼斯城为蓝本，建有长达数公里的运河和欧式建筑。游客可以乘坐贡多拉游船，感受异国情调，夜景尤为迷人。',
    image: 'https://picsum.photos/seed/venice/800/600',
    gallery: [
      'https://picsum.photos/seed/venice1/800/600',
      'https://picsum.photos/seed/venice2/800/600',
      'https://picsum.photos/seed/venice3/800/600',
    ],
    price: '免费（游船收费）',
    time: '全天',
  },
  {
    id: 'zoo',
    name: '大连森林动物园',
    type: 'park',
    shortDesc: '依山傍海的现代化动物园。',
    desc: '大连森林动物园位于白云山风景区内，依山傍海，环境优美。分为圈养区和散养区，可以观赏到大熊猫、金丝猴等珍稀动物。',
    image: 'https://picsum.photos/seed/zoo/800/600',
    gallery: [
      'https://picsum.photos/seed/zoo1/800/600',
      'https://picsum.photos/seed/zoo2/800/600',
      'https://picsum.photos/seed/zoo3/800/600',
    ],
    price: '¥120',
    time: '08:30-16:30',
  },
  {
    id: 'lingjiao-bay',
    name: '菱角湾',
    type: 'beach',
    shortDesc: '大连新晋网红打卡地，隔海相望渔人码头。',
    desc: '菱角湾位于大连南部海滨，与渔人码头隔海相望。这里有色彩斑斓的欧式建筑，是拍照打卡的绝佳地点，也是欣赏日落的好去处。',
    image: 'https://picsum.photos/seed/lingjiao/800/600',
    gallery: [
      'https://picsum.photos/seed/lingjiao1/800/600',
      'https://picsum.photos/seed/lingjiao2/800/600',
      'https://picsum.photos/seed/lingjiao3/800/600',
    ],
    price: '免费',
    time: '全天',
  },
  {
    id: 'cross-sea-bridge',
    name: '星海湾跨海大桥',
    type: 'square',
    shortDesc: '中国首座海上地锚式悬索跨海大桥。',
    desc: '星海湾跨海大桥全长约6公里，横跨星海湾海域。大桥不仅是重要的交通枢纽，更是大连一道亮丽的风景线，夜晚灯光璀璨，非常壮观。',
    image: 'https://picsum.photos/seed/bridge/800/600',
    gallery: [
      'https://picsum.photos/seed/bridge1/800/600',
      'https://picsum.photos/seed/bridge2/800/600',
      'https://picsum.photos/seed/bridge3/800/600',
    ],
    price: '免费',
    time: '全天',
  },
  {
    id: 'fujiazhuang',
    name: '付家庄公园',
    type: 'beach',
    shortDesc: '大连著名的海滨浴场，水清沙幼。',
    desc: '付家庄公园拥有大连市区内水质最好、沙滩最宽阔的海滨浴场。这里风景秀丽，海岛错落，是市民和游客夏日戏水、避暑的首选之地。',
    image: 'https://picsum.photos/seed/fujiazhuang/800/600',
    gallery: [
      'https://picsum.photos/seed/fujiazhuang1/800/600',
      'https://picsum.photos/seed/fujiazhuang2/800/600',
      'https://picsum.photos/seed/fujiazhuang3/800/600',
    ],
    price: '免费',
    time: '全天',
  },
  {
    id: 'fishermans-wharf',
    name: '渔人码头',
    type: 'beach',
    shortDesc: '充满北美风情的海滨休闲区。',
    desc: '大连渔人码头位于老虎滩海洋公园东侧，建筑风格仿造北美渔村。这里有众多特色餐厅、咖啡馆和酒吧，停泊着许多渔船，文艺气息浓厚。',
    image: 'https://picsum.photos/seed/wharf/800/600',
    gallery: [
      'https://picsum.photos/seed/wharf1/800/600',
      'https://picsum.photos/seed/wharf2/800/600',
      'https://picsum.photos/seed/wharf3/800/600',
    ],
    price: '免费',
    time: '全天',
  },
  {
    id: 'zhongshan-square',
    name: '中山广场',
    type: 'square',
    shortDesc: '大连的金融中心，环绕着众多近代历史建筑。',
    desc: '中山广场是大连市的标志性广场之一，呈圆形辐射状。广场周围环绕着十座建于上世纪初的欧式、日式建筑，被誉为“凝固的交响乐”。',
    image: 'https://picsum.photos/seed/zhongshan/800/600',
    gallery: [
      'https://picsum.photos/seed/zhongshan1/800/600',
      'https://picsum.photos/seed/zhongshan2/800/600',
      'https://picsum.photos/seed/zhongshan3/800/600',
    ],
    price: '免费',
    time: '全天',
  },
  {
    id: 'donggang',
    name: '东港商务区',
    type: 'square',
    shortDesc: '大连的“维多利亚港”，现代化的海滨新城。',
    desc: '东港商务区是大连的新兴核心区，拥有国际会议中心、音乐喷泉广场、游艇码头等现代化设施。这里的海景开阔，是散步、观海、看喷泉的绝佳去处。',
    image: 'https://picsum.photos/seed/donggang/800/600',
    gallery: [
      'https://picsum.photos/seed/donggang1/800/600',
      'https://picsum.photos/seed/donggang2/800/600',
      'https://picsum.photos/seed/donggang3/800/600',
    ],
    price: '免费',
    time: '全天',
  },
  {
    id: 'dalian-museum',
    name: '大连博物馆',
    type: 'museum',
    shortDesc: '了解大连近现代历史的最佳窗口。',
    desc: '大连博物馆位于星海广场西北侧，是一座展示大连城市历史与建设成就的综合性博物馆。馆内通过丰富的文物和多媒体展示，生动再现了大连从一个小渔村发展成为现代化国际都市的历程。',
    image: 'https://picsum.photos/seed/dalianmuseum/800/600',
    gallery: [
      'https://picsum.photos/seed/dalianmuseum1/800/600',
      'https://picsum.photos/seed/dalianmuseum2/800/600',
    ],
    price: '免费（需预约）',
    time: '09:00-17:00（周一闭馆）',
  },
  {
    id: 'natural-history-museum',
    name: '大连自然博物馆',
    type: 'museum',
    shortDesc: '探索自然奥秘，观赏巨鲸标本。',
    desc: '大连自然博物馆是一座集地质、古生物、动物、植物标本收藏、研究、展示于一体的综合性自然科学博物馆。馆内最有特色的是黑露脊鲸标本，是了解自然科学知识的绝佳场所。',
    image: 'https://picsum.photos/seed/naturalmuseum/800/600',
    gallery: [
      'https://picsum.photos/seed/naturalmuseum1/800/600',
      'https://picsum.photos/seed/naturalmuseum2/800/600',
    ],
    price: '免费（需预约）',
    time: '09:00-16:30（周一闭馆）',
  },
  {
    id: 'lushun-museum',
    name: '旅顺博物馆',
    type: 'museum',
    shortDesc: '国家一级博物馆，建筑本身即是艺术品。',
    desc: '旅顺博物馆位于旅顺口区，是大连唯一的国家一级博物馆。馆藏文物丰富，尤以西域文物、青铜器、陶瓷等闻名。博物馆建筑具有浓郁的异国风情，被列为全国重点文物保护单位。',
    image: 'https://picsum.photos/seed/lushunmuseum/800/600',
    gallery: [
      'https://picsum.photos/seed/lushunmuseum1/800/600',
      'https://picsum.photos/seed/lushunmuseum2/800/600',
    ],
    price: '免费（需预约）',
    time: '09:00-16:30（周一闭馆）',
  },
  {
    id: 'prison-museum',
    name: '旅顺日俄监狱旧址博物馆',
    type: 'museum',
    shortDesc: '铭记历史，见证近代苦难与抗争。',
    desc: '旅顺日俄监狱旧址博物馆是沙俄和日本侵略者在中国建立的一座监狱。这里记录了那段沉重的历史，是进行爱国主义教育的重要场所。',
    image: 'https://picsum.photos/seed/prisonmuseum/800/600',
    gallery: [
      'https://picsum.photos/seed/prisonmuseum1/800/600',
      'https://picsum.photos/seed/prisonmuseum2/800/600',
    ],
    price: '免费（需预约）',
    time: '09:00-16:00（周一闭馆）',
  },
  {
    id: 'art-museum',
    name: '大连美术馆',
    type: 'museum',
    shortDesc: '欧式老建筑里的艺术殿堂。',
    desc: '大连美术馆位于俄罗斯风情街，建筑原为东清轮船会社旧址，是一座典型的欧式建筑。馆内经常举办各类美术展览，是艺术爱好者的聚集地。',
    image: 'https://picsum.photos/seed/artmuseum/800/600',
    gallery: [
      'https://picsum.photos/seed/artmuseum1/800/600',
      'https://picsum.photos/seed/artmuseum2/800/600',
    ],
    price: '免费',
    time: '09:00-16:30（周一闭馆）',
  },
  {
    id: 'dalian-library-main',
    name: '大连图书馆主馆',
    type: 'museum',
    shortDesc: '白云山下的知识殿堂，现代化的大型图书馆。',
    desc: '大连图书馆主馆位于白云山风景区附近，建筑宏伟，环境幽雅。馆内藏书丰富，设施先进，是市民学习、阅读和进行文化交流的重要场所。',
    image: 'https://picsum.photos/seed/dallibmain/800/600',
    gallery: [
      'https://picsum.photos/seed/dallibmain1/800/600',
      'https://picsum.photos/seed/dallibmain2/800/600',
    ],
    price: '免费',
    time: '08:30-17:00',
  },
  {
    id: 'dalian-library-luxun',
    name: '大连图书馆鲁迅路分馆',
    type: 'museum',
    shortDesc: '被誉为“东亚最美图书馆”。',
    desc: '大连图书馆鲁迅路分馆原为满铁大连图书馆旧址，是一座具有百年历史的巴洛克式老建筑，被誉为“东亚最美图书馆”。馆内保留了古朴的木质书架和旋转楼梯，书香与历史气息交织，是感受大连近代文化底蕴的绝佳去处。',
    image: 'https://picsum.photos/seed/dallibluxun/800/600',
    gallery: [
      'https://picsum.photos/seed/dallibluxun1/800/600',
      'https://picsum.photos/seed/dallibluxun2/800/600',
    ],
    price: '免费',
    time: '08:30-17:00',
  },
];

export const foods = [
  {
    id: 'seaweed-bun',
    name: '海菜包子',
    shortDesc: '海鲜与面点的完美融合，鲜美多汁。',
    desc: '海菜包子是大连极具地方特色的面点。选用新鲜的海菜（如海麻线、裙带菜等）配以五花肉丁，皮薄馅大，咬一口鲜汁四溢，是大连人餐桌上的常客。',
    image: 'https://picsum.photos/seed/seaweedbun/800/600',
  },
  {
    id: 'oyster',
    name: '海蛎子',
    shortDesc: '大连人的“命根子”，鲜嫩多汁。',
    desc: '大连海蛎子（生蚝）以其肥美、鲜嫩而闻名。无论是生食、碳烤还是做成海蛎子蛾子，都能完美展现其独特的海洋鲜味。',
    image: 'https://picsum.photos/seed/oyster/800/600',
  },
  {
    id: 'menzi',
    name: '大连焖子',
    shortDesc: '地道的大连传统小吃，外焦里嫩。',
    desc: '焖子是大连的传统特色小吃，用地瓜淀粉熬制成块，切成小块在平底锅上煎至金黄，浇上芝麻酱、蒜泥等调料，香味扑鼻。',
    image: 'https://picsum.photos/seed/menzi/800/600',
  },
  {
    id: 'salted-fish',
    name: '咸鱼饼子',
    shortDesc: '渔家风味的经典组合，咸香酥脆。',
    desc: '新鲜的海鱼经腌制晾晒后，与玉米面饼子一同下锅煎烤。鱼肉咸鲜，饼子酥脆，是极具大连特色的渔家美味。',
    image: 'https://picsum.photos/seed/saltedfish/800/600',
  },
  {
    id: 'dumplings',
    name: '海鲜饺子',
    shortDesc: '皮薄馅大，满口海洋的味道。',
    desc: '以鲅鱼、虾仁、海螺等新鲜海味入馅，皮薄多汁。尤其是鲅鱼水饺，口感细腻鲜美，是大连面食的代表。',
    image: 'https://picsum.photos/seed/dumplings/800/600',
  },
  {
    id: 'bbq',
    name: '大连烧烤',
    shortDesc: '万物皆可烤，铁板鱿鱼是灵魂。',
    desc: '大连烧烤以海鲜为主，铁板鱿鱼更是街头巷尾的招牌。秘制酱料配合新鲜食材，是夏日夜晚的最佳伴侣。',
    image: 'https://picsum.photos/seed/bbq/800/600',
  },
];

export const famousSnacks = [
  { name: '铁板鱿鱼', desc: '新鲜鱿鱼煎制，香辣嚼劲', rating: 4.8, image: 'https://picsum.photos/seed/youyu/400/300' },
  { name: '海菜包子', desc: '海菜猪肉作馅，鲜汁四溢', rating: 4.7, image: 'https://picsum.photos/seed/baozi/400/300' },
  { name: '大连焖子', desc: '地瓜粉煎炒制，外焦里嫩', rating: 4.9, image: 'https://picsum.photos/seed/menzi2/400/300' },
  { name: '咸鱼饼子', desc: '咸鱼配玉米饼，咸香酥脆', rating: 4.6, image: 'https://picsum.photos/seed/xianyu/400/300' },
  { name: '蚬子面', desc: '新鲜蚬子熬汤，鲜香暖胃', rating: 4.5, image: 'https://picsum.photos/seed/mian/400/300' },
  { name: '炸虾球', desc: '鲜虾仁裹糊炸，外脆里嫩', rating: 4.7, image: 'https://picsum.photos/seed/xiaqiu/400/300' },
  { name: '烤鱼片', desc: '鳕鱼轻烤成型，松脆鲜香', rating: 4.4, image: 'https://picsum.photos/seed/yupian/400/300' },
  { name: '海凉粉', desc: '牛毛菜熬制成，清凉爽滑', rating: 4.6, image: 'https://picsum.photos/seed/liangfen/400/300' },
  { name: '海鲜饺子', desc: '鲅鱼虾肉作馅，鲜汁满溢', rating: 4.8, image: 'https://picsum.photos/seed/jiaozi/400/300' },
  { name: '糖鼓火烧', desc: '传统面点烤制，香甜酥脆', rating: 4.3, image: 'https://picsum.photos/seed/huoshao/400/300' },
];

export const famousDishes = [
  { name: '红烤全虾', desc: '大对虾慢火烤，鲜甜火红', rating: 4.9, image: 'https://picsum.photos/seed/quanxia/400/300' },
  { name: '葱烧海参', desc: '辽参与葱烧制，葱香软糯', rating: 4.8, image: 'https://picsum.photos/seed/haishen/400/300' },
  { name: '油爆海螺', desc: '海螺猛火爆炒，脆嫩咸鲜', rating: 4.7, image: 'https://picsum.photos/seed/hailuo/400/300' },
  { name: '辣炒蚬子', desc: '花蛤辣炒入味，鲜辣多汁', rating: 4.8, image: 'https://picsum.photos/seed/xianzi/400/300' },
  { name: '海鲜焖子', desc: '凉粉海鲜同炒，滑嫩鲜香', rating: 4.6, image: 'https://picsum.photos/seed/haixianmenzi/400/300' },
  { name: '大连鲍鱼', desc: '皱纹盘鲍蒸制，细嫩鲜美', rating: 4.9, image: 'https://picsum.photos/seed/baoyu/400/300' },
  { name: '五彩扇贝', desc: '扇贝蛋清蒸制，清淡爽口', rating: 4.5, image: 'https://picsum.photos/seed/shanbei/400/300' },
  { name: '海鲜全家福', desc: '多种海鲜杂烩，鲜浓醇厚', rating: 4.7, image: 'https://picsum.photos/seed/quanjiafu/400/300' },
  { name: '焖渤海刀', desc: '渤海刀鱼家焖，香鲜嫩滑', rating: 4.6, image: 'https://picsum.photos/seed/daoyu/400/300' },
  { name: '苏扬大烤', desc: '嫩滑肉片腌烤，甜咸交织', rating: 4.4, image: 'https://picsum.photos/seed/dakao/400/300' },
];

export const foodStreets = [
  { name: '中原小吃街', desc: '老味聚集满街，焖子炸串超解馋', rating: 4.7, image: 'https://picsum.photos/seed/zhongyuan/400/300' },
  { name: '西安路小吃街', desc: '商圈美食扎堆，烤鱿鱼炸鸡多元选', rating: 4.6, image: 'https://picsum.photos/seed/xianlu/400/300' },
  { name: '天津街美食街', desc: '夜市烟火超旺，海鲜烧烤香满巷', rating: 4.5, image: 'https://picsum.photos/seed/tianjin/400/300' },
  { name: '太原街夜市', desc: '夜晚人气火爆，特色小吃种类全', rating: 4.8, image: 'https://picsum.photos/seed/taiyuan/400/300' },
  { name: '俄罗斯风情街', desc: '俄式建筑环绕，俄式小吃任你尝', rating: 4.4, image: 'https://picsum.photos/seed/russia/400/300' },
  { name: '交大夜市', desc: '学生食客扎堆，亲民美味超实惠', rating: 4.7, image: 'https://picsum.photos/seed/jiaoda/400/300' },
  { name: '青泥洼桥街', desc: '商圈核心地带，中西美食全都有', rating: 4.6, image: 'https://picsum.photos/seed/qingniwa/400/300' },
  { name: '二七广场夜市', desc: '老城区烟火气，地道小吃接地气', rating: 4.5, image: 'https://picsum.photos/seed/erqi/400/300' },
  { name: '高新万达金街', desc: '潮流美食聚集，年轻人打卡圣地', rating: 4.6, image: 'https://picsum.photos/seed/gaoxin/400/300' },
  { name: '渔人码头美食区', desc: '海边浪漫风情，海鲜西餐两相宜', rating: 4.7, image: 'https://picsum.photos/seed/yuren/400/300' },
];

export const famousRestaurants = {
  economy: [
    { name: '小船渔村', desc: '三鲜焖子、黄花鱼丸汤，地道本地味', price: '85', rating: 4.6, image: 'https://picsum.photos/seed/xiaochuan/400/300' },
    { name: '日月明小渔村', desc: '辣炒蚬子、咸鱼饼子，平价鲜掉眉', price: '75', rating: 4.5, image: 'https://picsum.photos/seed/riyue/400/300' },
    { name: '日月昇渔家菜', desc: '海鲜烩饼、酱焖海兔，家常味超正', price: '70', rating: 4.5, image: 'https://picsum.photos/seed/riyuesheng2/400/300' },
    { name: '喜鼎海胆水饺', desc: '招牌海胆水饺，鲜甜多汁，环境雅致', price: '95', rating: 4.7, image: 'https://picsum.photos/seed/xiding/400/300' },
    { name: '68度大连老菜', desc: '糖醋黄花鱼、熘肝尖，老大连的情怀', price: '80', rating: 4.4, image: 'https://picsum.photos/seed/68degree/400/300' },
  ],
  banquet: [
    { name: '品海楼', desc: '清蒸鲍鱼、海鲜全家福，海鲜品质高', price: '150', rating: 4.8, image: 'https://picsum.photos/seed/pinhailou2/400/300' },
    { name: '海味当家', desc: '现捞海鲜蒸、蒜蓉粉丝扇贝，原汁原味鲜', price: '180', rating: 4.7, image: 'https://picsum.photos/seed/haiwei/400/300' },
    { name: '渔港明珠', desc: '帝王蟹姿造、东星斑，高端海鲜宴', price: '400', rating: 4.9, image: 'https://picsum.photos/seed/yugang/400/300' },
    { name: '万宝海鲜舫', desc: '大连海鲜殿堂，装修奢华，食材顶级', price: '500', rating: 4.9, image: 'https://picsum.photos/seed/wanbao/400/300' },
    { name: '天天渔港', desc: '经典老牌海鲜，口味稳定，宴请首选', price: '260', rating: 4.6, image: 'https://picsum.photos/seed/tiantian/400/300' },
  ],
};

export const restaurantRecommendations = [
  {
    id: 'pinhailou',
    name: '品海楼',
    desc: '大连老牌海鲜名店，装修极具大连特色，是体验大连海鲜文化的绝佳去处。',
    specialties: ['品海小炙', '金牌脆皮虾', '海鲜全家福'],
    avgPrice: 150,
    rating: 4.8,
    image: 'https://picsum.photos/seed/pinhailou/400/300',
    address: '大连市中山区滨海东路72号',
  },
  {
    id: 'xiaochuanyucun',
    name: '小船渔村',
    desc: '深受本地人喜爱的平价海鲜馆，食材新鲜，口味地道。',
    specialties: ['三鲜焖子', '黄花鱼丸汤', '生烤鱿鱼'],
    avgPrice: 85,
    rating: 4.6,
    image: 'https://picsum.photos/seed/xiaochuanyucun/400/300',
    address: '大连市沙河口区中山路608-8号',
  },
  {
    id: 'haiweidangjia',
    name: '海味当家',
    desc: '主打原汁原味的蒸汽海鲜，保留了海鲜最原始的鲜甜。',
    specialties: ['蒸汽海鲜拼盘', '蒜蓉粉丝扇贝', '海鲜粥'],
    avgPrice: 180,
    rating: 4.7,
    image: 'https://picsum.photos/seed/haiweidangjia/400/300',
    address: '大连市中山区港隆路10号',
  },
  {
    id: 'riyuesheng',
    name: '日月昇渔家菜',
    desc: '大连家喻户晓的连锁渔家菜馆，分量足，性价比极高。',
    specialties: ['海鲜烩饼', '酱焖海兔', '咸鱼饼子'],
    avgPrice: 70,
    rating: 4.5,
    image: 'https://picsum.photos/seed/riyuesheng/400/300',
    address: '大连市西岗区拥警路10号',
  },
  {
    id: 'yugangmingzhu',
    name: '渔港明珠',
    desc: '高端海鲜宴请的首选，环境优雅，服务一流，食材极其考究。',
    specialties: ['帝王蟹姿造', '东星斑', '佛跳墙'],
    avgPrice: 400,
    rating: 4.9,
    image: 'https://picsum.photos/seed/yugangmingzhu/400/300',
    address: '大连市中山区滨海东路',
  },
  {
    id: 'wanbao',
    name: '万宝海鲜舫',
    desc: '大连海鲜殿堂，装修奢华，食材顶级，是体验大连高端海鲜的必选之地。',
    specialties: ['极品鲍鱼', '深海大龙虾', '燕鲍翅宴'],
    avgPrice: 500,
    rating: 4.9,
    image: 'https://picsum.photos/seed/wanbao/400/300',
    address: '大连市中山区解放路108号',
  },
];

export const hotels = [
  {
    id: 'castle',
    name: '大连一方城堡豪华精选酒店',
    shortDesc: '童话般的城堡酒店，俯瞰星海湾。',
    desc: '坐落于莲花山脉，俯瞰星海湾，建筑风格宛如欧洲古典城堡。提供奢华的住宿体验 and 无与伦比的海景。',
    image: 'https://picsum.photos/seed/castle/800/600',
    price: '¥1500起',
    priceValue: 1500,
    address: '大连市沙河口区滨海西路603号',
  },
  {
    id: 'conrad',
    name: '大连康莱德酒店',
    shortDesc: '东港商务区的奢华之选。',
    desc: '位于东港商务区，毗邻大连国际会议中心，提供现代奢华的客房和一流的设施，是商务和休闲的理想选择。',
    image: 'https://picsum.photos/seed/conrad/800/600',
    price: '¥1000起',
    priceValue: 1000,
    address: '大连市中山区人民东路31号',
  },
  {
    id: 'grand-hyatt',
    name: '大连君悦酒店',
    shortDesc: '星海广场畔的豪华海景酒店。',
    desc: '位于星海广场，紧邻星海湾沙滩，客房拥有全景落地窗，可尽赏无敌海景和星海广场的繁华景色。',
    image: 'https://picsum.photos/seed/grandhyatt/800/600',
    price: '¥1200起',
    priceValue: 1200,
    address: '大连市沙河口区星海广场C3区33号',
  },
  {
    id: 'crowne-plaza-xinghai',
    name: '大连星海皇冠假日酒店',
    shortDesc: '星海广场商圈的高端商务酒店。',
    desc: '地处星海广场核心区域，交通便利，设施完善，是商务出行和休闲旅游的优质选择。',
    image: 'https://picsum.photos/seed/crowneplaza/800/600',
    price: '¥800起',
    priceValue: 800,
    address: '大连市沙河口区星海广场C1区32号',
  },
  {
    id: 'ji-hotel-xinghai',
    name: '全季大连星海广场酒店',
    shortDesc: '简约舒适的星海广场周边住宿。',
    desc: '全季酒店以简约、舒适、自然的设计理念，为旅客提供高品质的住宿体验，距离星海广场仅几步之遥。',
    image: 'https://picsum.photos/seed/jihotel/800/600',
    price: '¥400起',
    priceValue: 400,
    address: '大连市沙河口区中山路588号',
  },
  {
    id: 'atour-xinghai',
    name: '大连星海广场海景亚朵酒店',
    shortDesc: '充满人文气息的海景酒店。',
    desc: '亚朵酒店以阅读和属地摄影为主题，提供高品质的客房设施和贴心的服务，部分客房可观赏美丽海景。',
    image: 'https://picsum.photos/seed/atour/800/600',
    price: '¥500起',
    priceValue: 500,
    address: '大连市沙河口区星海广场B3区10号',
  },
  {
    id: 'intercontinental',
    name: '中远海运洲际酒店',
    shortDesc: '中山广场商圈的经典奢华酒店。',
    desc: '位于大连市中心友好广场，地理位置优越，客房宽敞舒适，餐饮选择丰富，是体验大连城市魅力的理想下榻之所。',
    image: 'https://picsum.photos/seed/intercontinental/800/600',
    price: '¥900起',
    priceValue: 900,
    address: '大连市中山区友好广场6号',
  },
  {
    id: 'shangri-la',
    name: '大连香格里拉大酒店',
    shortDesc: '人民路商务区的标志性豪华酒店。',
    desc: '位于大连市中心的人民路，提供香格里拉标志性的热情好客服务，拥有多个屡获殊荣的餐厅和完善的休闲设施。',
    image: 'https://picsum.photos/seed/shangrila/800/600',
    price: '¥850起',
    priceValue: 850,
    address: '大连市中山区人民路66号',
  },
  {
    id: 'qingju-donggang',
    name: '东港商务区国际会议中心轻居酒店',
    shortDesc: '东港商务区的年轻时尚酒店。',
    desc: '亚朵集团旗下轻居品牌，设计年轻时尚，充满活力，紧邻大连国际会议中心和东港音乐喷泉，出行十分便利。',
    image: 'https://picsum.photos/seed/qingju/800/600',
    price: '¥450起',
    priceValue: 450,
    address: '大连市中山区人民东路41号',
  },
  {
    id: 'hanting-zhongshan',
    name: '汉庭酒店大连中山广场店',
    shortDesc: '中山广场核心区域的经济连锁酒店。',
    desc: '位于中山广场金融圈，交通极其便利，周边历史建筑环绕。提供干净、舒适、标准化的住宿服务，是预算有限游客的理想选择。',
    image: 'https://picsum.photos/seed/hanting/800/600',
    price: '¥280起',
    priceValue: 280,
    address: '大连市中山区玉光街11号',
  },
  {
    id: '7days-railway',
    name: '7天酒店大连火车站店',
    shortDesc: '火车站周边的便捷住宿。',
    desc: '紧邻大连火车站和胜利广场商圈，地理位置优越，出行非常方便。提供基础但整洁的客房，性价比极高。',
    image: 'https://picsum.photos/seed/7days/800/600',
    price: '¥190起',
    priceValue: 190,
    address: '大连市中山区长江路180号',
  },
  {
    id: 'homeinn-qingniwa',
    name: '如家酒店大连青泥洼桥店',
    shortDesc: '青泥洼桥商圈的温馨住宿。',
    desc: '位于大连最繁华的青泥洼桥商圈，周边商场林立，美食众多。酒店秉承如家一贯的温馨服务，让您在旅途中感受到家的温暖。',
    image: 'https://picsum.photos/seed/homeinn/800/600',
    price: '¥260起',
    priceValue: 260,
    address: '大连市中山区解放路26号',
  },
  {
    id: 'ibis-shengli',
    name: '宜必思酒店大连胜利广场店',
    shortDesc: '法式时尚风格的经济型酒店。',
    desc: '位于胜利广场商圈，设计简约时尚，客房设施现代，提供高品质的睡眠体验。周边交通便利，购物餐饮选择丰富。',
    image: 'https://picsum.photos/seed/ibis/800/600',
    price: '¥320起',
    priceValue: 320,
    address: '大连市中山区天津街201号',
  },
  {
    id: 'orange-hotel-xianlu',
    name: '桔子酒店大连西安路店',
    shortDesc: '西安路商圈的设计感酒店。',
    desc: '位于西安路商业中心，设计风格独特，充满现代感。客房配备智能设施，提供舒适且具有个性的住宿环境。',
    image: 'https://picsum.photos/seed/orange/800/600',
    price: '¥380起',
    priceValue: 380,
    address: '大连市沙河口区西安路123号',
  },
];

export const routes = [
  {
    id: '3-days',
    name: '大连经典3日游',
    shortDesc: '涵盖大连最精华景点的经典路线。',
    desc: '第一天：星海广场 -> 滨海路 -> 老虎滩海洋公园\n第二天：金石滩国家旅游度假区 -> 发现王国\n第三天：东港威尼斯水城 -> 俄罗斯风情街',
    image: 'https://picsum.photos/seed/route3/800/600',
    days: 3,
  },
  {
    id: '2-days-family',
    name: '大连亲子2日游',
    shortDesc: '适合带孩子游玩的轻松路线。',
    desc: '第一天：大连森林动物园 -> 圣亚海洋世界\n第二天：发现王国主题公园',
    image: 'https://picsum.photos/seed/route2/800/600',
    days: 2,
  },
  {
    id: 'coastline-scenic',
    name: '最美海岸线徒步/自驾之旅',
    shortDesc: '沿着大连最美的滨海路，感受山海间的浪漫。',
    desc: '路线：棒棰岛 -> 海之韵公园 -> 滨海路徒步 -> 燕窝岭 -> 傅家庄 -> 银沙滩 -> 星海湾大桥观景台\n亮点：这条路线串联了大连最精华的海岸景观，每一站都是绝佳的拍照点。',
    image: 'https://picsum.photos/seed/coastline/800/600',
    days: 1,
  },
  {
    id: 'indoor-culture',
    name: '城市文化与艺术室内之旅',
    shortDesc: '避开风雨，深入了解大连的历史与艺术底蕴。',
    desc: '路线：大连博物馆 -> 大连自然博物馆 -> 大连美术馆 -> 鲁迅路老图书馆 -> 东方水城美术馆群\n亮点：全程室内或欧式老建筑，适合文艺青年和亲子家庭，深度感受城市文化。',
    image: 'https://picsum.photos/seed/indoor/800/600',
    days: 1,
  },
  {
    id: 'foodie-paradise',
    name: '舌尖上的大连美食之旅',
    shortDesc: '从清晨到深夜，吃遍大连最地道的味道。',
    desc: '上午：中原小吃街（海菜包子、焖子）\n中午：品海楼或小船渔村（地道海鲜）\n下午：渔人码头咖啡馆下午茶\n晚上：西安路夜市或交大夜市（铁板鱿鱼、烧烤）\n亮点：一站式打卡大连特色小吃和高端海鲜，满足你的味蕾。',
    image: 'https://picsum.photos/seed/foodroute/800/600',
    days: 1,
  },
];
